services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5401:5432"
    volumes:
      - edge_red_db_data:/var/lib/postgresql/data

volumes:
  edge_red_db_data: