version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: your_userpostgresname
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - edge_red_db_data:/var/lib/postgresql/data

volumes:
  edge_red_db_data: